<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGn4xlwx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGn4xlwx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGn4xlwx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGn4xlwx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGn4xlwx\appDevDebugProjectContainer([
    'container.build_hash' => 'Gn4xlwx',
    'container.build_id' => 'c0a93027',
    'container.build_time' => 1637008802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGn4xlwx');
